route:
  group_by: 
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-notifications

receivers:
  - name: email-notifications
    email_configs:
      - to: jaiswaladi246@gmail.com
        from: test@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: rubinafayeen58@gmail.com
        auth_identity: rubinafayeen58@gmail.com
        auth_password: "{put your password}"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - alertname
      - instance
